"use strict";
(function(){
const DATA_URL="data/a1-lessons.json";
let lesson=null,stage="explanation",practiceScore=0,trainerScore=0,assessmentScore=0,weak={};
const root=()=>document.getElementById("grammarSection");
const lang=()=>document.getElementById("language")?.value||"ru";
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const ui={ru:{back:"← Маршрут A1",listen:"🔊 Слушать",start:"Начать практику",next:"Дальше",check:"Проверить",correct:"Правильно",wrong:"Неправильно",practice:"Практика",trainer:"Тренажёр",assessment:"Контроль",result:"Результат",review:"Повторение",repeat:"Повторить урок",route:"Вернуться к маршруту A1",mastered:"Тема усвоена",almost:"Хороший результат, но есть что повторить",again:"Тему лучше пройти ещё раз",weak:"Слабые места",noWeak:"Ошибок в контроле нет",planned:"Следующий урок пока готовится"},uk:{back:"← Маршрут A1",listen:"🔊 Слухати",start:"Почати практику",next:"Далі",check:"Перевірити",correct:"Правильно",wrong:"Неправильно",practice:"Практика",trainer:"Тренажер",assessment:"Контроль",result:"Результат",review:"Повторення",repeat:"Повторити урок",route:"Повернутися до маршруту A1",mastered:"Тему засвоєно",almost:"Гарний результат, але є що повторити",again:"Тему краще пройти ще раз",weak:"Слабкі місця",noWeak:"Помилок у контролі немає",planned:"Наступний урок ще готується"},en:{back:"← A1 route",listen:"🔊 Listen",start:"Start practice",next:"Continue",check:"Check",correct:"Correct",wrong:"Incorrect",practice:"Practice",trainer:"Trainer",assessment:"Assessment",result:"Result",review:"Review",repeat:"Repeat lesson",route:"Back to A1 route",mastered:"Topic mastered",almost:"Good result, but review a few points",again:"It is better to repeat the lesson",weak:"Weak spots",noWeak:"No assessment mistakes",planned:"The next lesson is still being prepared"},es:{back:"← Ruta A1",listen:"🔊 Escuchar",start:"Empezar práctica",next:"Continuar",check:"Comprobar",correct:"Correcto",wrong:"Incorrecto",practice:"Práctica",trainer:"Entrenador",assessment:"Evaluación",result:"Resultado",review:"Repaso",repeat:"Repetir lección",route:"Volver a la ruta A1",mastered:"Tema dominado",almost:"Buen resultado, pero conviene repasar algunos puntos",again:"Conviene repetir la lección",weak:"Puntos débiles",noWeak:"No hay errores en la evaluación",planned:"La siguiente lección todavía se está preparando"}};
const U=()=>ui[lang()]||ui.ru;
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function speak(word){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const x=new SpeechSynthesisUtterance(word);x.lang="es-ES";x.rate=.8;window.speechSynthesis.speak(x);}
function setView(){document.querySelector(".trainer")?.style.setProperty("display","none");const r=root();if(r)r.style.display="block";}
function stepper(active){const labels=["explanation","practice","trainer","assessment","result"];const names={explanation:"1. 📖",practice:"2. ✍️",trainer:"3. 🏋️",assessment:"4. ✅",result:"5. 🏆"};return `<div class="a1-stepper">${labels.map(s=>`<span class="${s===active?"active":""}">${names[s]}</span>`).join("")}</div>`;}
function renderExplanation(){stage="explanation";setView();const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru;r.innerHTML=`<div class="a1-lesson"><button class="a1-back" id="a1Back">${U().back}</button>${stepper(stage)}<div class="a1-kicker">A1 · ${esc(t.title)}</div><h2>${esc(t.title)}</h2><p class="a1-goal">${esc(t.goal)}</p><p>${esc(t.intro)}</p><div class="a1-rule-grid">${t.rules.map(([h,p])=>`<article><h3>${esc(h)}</h3><p>${esc(p)}</p></article>`).join("")}</div><h3>${esc(t.examplesTitle)}</h3><div class="a1-example-grid">${lesson.examples.map(x=>`<button type="button" class="a1-example" data-word="${esc(x.word)}"><strong>${esc(x.word)}</strong><small>${U().listen}</small></button>`).join("")}</div><button class="grammar-primary a1-main" id="a1Start">${U().start}</button></div>`;r.querySelectorAll("[data-word]").forEach(b=>b.onclick=()=>speak(b.dataset.word));document.getElementById("a1Back").onclick=()=>window.openA1Curriculum?.();document.getElementById("a1Start").onclick=()=>runStage("practice",6);}
function localizedOptions(q){return q.optionsByLang?.[lang()]||q.options;}
function correctAnswer(q){return q.answers?.[lang()]||q.answer;}
function runStage(kind,count){stage=kind;const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru,items=shuffle(lesson.questionBank).slice(0,count);let i=0,score=0;const title=kind==="practice"?t.practiceTitle:kind==="trainer"?t.trainerTitle:t.assessmentTitle;function show(){if(i>=items.length){if(kind==="practice"){practiceScore=score;return runStage("trainer",8)}if(kind==="trainer"){trainerScore=score;return runStage("assessment",10)}assessmentScore=score;return renderResult(items.length)}const q=items[i],opts=localizedOptions(q);r.innerHTML=`<div class="a1-lesson">${stepper(kind)}<div class="a1-kicker">A1 · ${esc(title)}</div><div class="a1-question-card"><div class="a1-counter">${i+1} / ${items.length}</div><h2>${esc(q.prompt[lang()]||q.prompt.ru)}</h2><div class="a1-options">${opts.map(o=>`<button type="button" data-answer="${esc(o)}">${esc(o)}</button>`).join("")}</div><p id="a1Feedback"></p></div></div>`;r.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>check(q,b.dataset.answer));}function check(q,value){const ok=value===correctAnswer(q);if(ok)score++;else weak[q.tag]=(weak[q.tag]||0)+1;const f=document.getElementById("a1Feedback");if(f)f.textContent=ok?`✅ ${U().correct}`:`❌ ${U().wrong}: ${correctAnswer(q)}`;r.querySelectorAll("[data-answer]").forEach(b=>b.disabled=true);setTimeout(()=>{i++;show()},kind==="assessment"?350:650);}show();}
function renderResult(total){stage="result";const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru,percent=Math.round(assessmentScore/total*100),weakTags=Object.entries(weak).sort((a,b)=>b[1]-a[1]);const msg=percent>=90?U().mastered:percent>=70?U().almost:U().again;window.progressRecordLesson?.("A1",lesson.id,{percent,practice:practiceScore,trainer:trainerScore,assessment:assessmentScore,weakSpots:Object.fromEntries(weakTags),nextLessonId:lesson.nextLessonId});r.innerHTML=`<div class="a1-lesson">${stepper(stage)}<div class="a1-result"><div class="a1-score">${percent}%</div><h2>${esc(msg)}</h2><p>${esc(t.resultTitle)}: ${assessmentScore}/${total} · ${U().practice}: ${practiceScore}/6 · ${U().trainer}: ${trainerScore}/8</p><h3>${U().weak}</h3><div class="a1-weak-list">${weakTags.length?weakTags.map(([k,v])=>`<span>${esc(k)} · ${v}</span>`).join(""):esc(U().noWeak)}</div><p><strong>${esc(t.nextTitle)}</strong><br>${esc(U().planned)}</p><div class="a1-result-actions"><button class="grammar-primary" id="a1Repeat">${U().repeat}</button><button id="a1Route">${U().route}</button></div></div></div>`;document.getElementById("a1Repeat").onclick=()=>{practiceScore=trainerScore=assessmentScore=0;weak={};renderExplanation()};document.getElementById("a1Route").onclick=()=>window.openA1Curriculum?.();}
async function openLesson(id){try{const res=await fetch(DATA_URL,{cache:"no-store"});if(!res.ok)throw new Error("A1 lessons load failed");const data=await res.json();if(!data[id])return;lesson={id,...data[id]};practiceScore=trainerScore=assessmentScore=0;weak={};renderExplanation();}catch(e){console.error(e);}}
document.addEventListener("esprofe:a1Topic",e=>openLesson(e.detail?.topicId));document.addEventListener("esprofe:languageChanged",()=>{if(lesson&&root()?.style.display==="block"&&stage==="explanation")renderExplanation();});window.openA1Lesson=openLesson;
})();