"use strict";
(function(){
const DATA_URL="data/a1-lessons.json";
let lesson=null,stage="explanation",practiceScore=0,trainerScore=0,assessmentScore=0,weak={};
const root=()=>document.getElementById("grammarSection");
const lang=()=>document.getElementById("language")?.value||"ru";
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const ui={
ru:{back:"← Маршрут A1",listen:"🔊 Слушать",examples:"Перейти к примерам",start:"Начать практику",next:"Дальше",correct:"Правильно",wrong:"Неправильно",practice:"Практика",trainer:"Тренажёр",assessment:"Контроль",result:"Результат",review:"Повторение",repeat:"Повторить урок",repeatAssessment:"Повторить контроль",reviewErrors:"Разобрать ошибки",route:"Вернуться к маршруту A1",mastered:"Тема усвоена",almost:"Хороший результат, но есть что повторить",again:"Тему лучше пройти ещё раз",weak:"Слабые места",noWeak:"Ошибок в контроле нет",planned:"Следующий урок пока готовится"},
uk:{back:"← Маршрут A1",listen:"🔊 Слухати",examples:"Перейти до прикладів",start:"Почати практику",next:"Далі",correct:"Правильно",wrong:"Неправильно",practice:"Практика",trainer:"Тренажер",assessment:"Контроль",result:"Результат",review:"Повторення",repeat:"Повторити урок",repeatAssessment:"Повторити контроль",reviewErrors:"Розібрати помилки",route:"Повернутися до маршруту A1",mastered:"Тему засвоєно",almost:"Гарний результат, але є що повторити",again:"Тему краще пройти ще раз",weak:"Слабкі місця",noWeak:"Помилок у контролі немає",planned:"Наступний урок ще готується"},
en:{back:"← A1 route",listen:"🔊 Listen",examples:"Go to examples",start:"Start practice",next:"Continue",correct:"Correct",wrong:"Incorrect",practice:"Practice",trainer:"Trainer",assessment:"Assessment",result:"Result",review:"Review",repeat:"Repeat lesson",repeatAssessment:"Repeat assessment",reviewErrors:"Review mistakes",route:"Back to A1 route",mastered:"Topic mastered",almost:"Good result, but review a few points",again:"It is better to repeat the lesson",weak:"Weak spots",noWeak:"No assessment mistakes",planned:"The next lesson is still being prepared"},
es:{back:"← Ruta A1",listen:"🔊 Escuchar",examples:"Ir a los ejemplos",start:"Empezar práctica",next:"Continuar",correct:"Correcto",wrong:"Incorrecto",practice:"Práctica",trainer:"Entrenador",assessment:"Evaluación",result:"Resultado",review:"Repaso",repeat:"Repetir lección",repeatAssessment:"Repetir evaluación",reviewErrors:"Revisar errores",route:"Volver a la ruta A1",mastered:"Tema dominado",almost:"Buen resultado, pero conviene repasar algunos puntos",again:"Conviene repetir la lección",weak:"Puntos débiles",noWeak:"No hay errores en la evaluación",planned:"La siguiente lección todavía se está preparando"}
};
const U=()=>ui[lang()]||ui.ru;
const tagRule={vowels:0,h:1,"ñ":2,"j-g":3,"c-z":4,"r-rr":5,stress:6};
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function speak(word){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const x=new SpeechSynthesisUtterance(word);x.lang="es-ES";x.rate=.8;window.speechSynthesis.speak(x);}
function setView(){document.querySelector(".trainer")?.style.setProperty("display","none");const r=root();if(r)r.style.display="block";}
function stepper(active){const labels=["explanation","examples","practice","trainer","assessment","result","review"];return `<div class="a1-stepper a1-stepper-seven">${labels.map(s=>`<span class="${s===active?"active":""}" title="${esc(s)}"></span>`).join("")}</div>`;}
function renderExplanation(){stage="explanation";setView();const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru;r.innerHTML=`<div class="a1-lesson"><button class="a1-back" id="a1Back">${U().back}</button>${stepper(stage)}<div class="a1-kicker">A1 · ${esc(t.title)}</div><h2>${esc(t.title)}</h2><p class="a1-goal">${esc(t.goal)}</p><p>${esc(t.intro)}</p><div class="a1-rule-grid">${t.rules.map(([h,p])=>`<article><h3>${esc(h)}</h3><p>${esc(p)}</p></article>`).join("")}</div><button class="grammar-primary a1-main" id="a1Examples">${U().examples}</button></div>`;document.getElementById("a1Back").onclick=()=>window.openA1Curriculum?.();document.getElementById("a1Examples").onclick=renderExamples;}
function renderExamples(){stage="examples";const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru;r.innerHTML=`<div class="a1-lesson">${stepper(stage)}<div class="a1-kicker">A1 · ${esc(t.examplesTitle)}</div><h2>${esc(t.examplesTitle)}</h2><p>${esc(t.goal)}</p><div class="a1-example-grid">${lesson.examples.map(x=>`<button type="button" class="a1-example" data-word="${esc(x.word)}"><strong>${esc(x.word)}</strong><small>${U().listen}</small></button>`).join("")}</div><button class="grammar-primary a1-main" id="a1Start">${U().start}</button></div>`;r.querySelectorAll("[data-word]").forEach(b=>b.onclick=()=>speak(b.dataset.word));document.getElementById("a1Start").onclick=()=>runStage("practice",6);}
function localizedOptions(q){const raw=q.optionsByLang?.[lang()]??q.optionsByLang?.ru??q.options;return Array.isArray(raw)?raw:[];}
function correctAnswer(q){return q.answers?.[lang()]??q.answers?.ru??q.answer??"";}
function runStage(kind,count){stage=kind;const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru,items=shuffle(lesson.questionBank).slice(0,Math.min(count,lesson.questionBank.length));let i=0,score=0;const title=kind==="practice"?t.practiceTitle:kind==="trainer"?t.trainerTitle:t.assessmentTitle;
function show(){if(i>=items.length){if(kind==="practice"){practiceScore=score;return runStage("trainer",8)}if(kind==="trainer"){trainerScore=score;return runStage("assessment",10)}assessmentScore=score;return renderResult(items.length)}const q=items[i],opts=shuffle(localizedOptions(q));r.innerHTML=`<div class="a1-lesson">${stepper(kind)}<div class="a1-kicker">A1 · ${esc(title)}</div><div class="a1-question-card"><div class="a1-counter">${i+1} / ${items.length}</div><h2>${esc(q.prompt?.[lang()]||q.prompt?.ru||q.prompt||"")}</h2><div class="a1-options">${opts.map((o,n)=>`<button type="button" class="a1-option" data-option-index="${n}">${esc(o)}</button>`).join("")}</div><p id="a1Feedback" aria-live="polite"></p></div></div>`;r.querySelectorAll("[data-option-index]").forEach(b=>b.onclick=()=>check(q,opts[Number(b.dataset.optionIndex)]));}
function check(q,value){const answer=correctAnswer(q),ok=value===answer;if(ok)score++;else weak[q.tag]=(weak[q.tag]||0)+1;const f=document.getElementById("a1Feedback");if(f)f.textContent=ok?`✅ ${U().correct}`:`❌ ${U().wrong}: ${answer}`;r.querySelectorAll("[data-option-index]").forEach(b=>b.disabled=true);setTimeout(()=>{i++;show()},kind==="assessment"?350:650);}show();}
function renderResult(total){stage="result";const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru,percent=Math.round(assessmentScore/total*100),weakTags=Object.entries(weak).sort((a,b)=>b[1]-a[1]),msg=percent>=90?U().mastered:percent>=70?U().almost:U().again;window.progressRecordLesson?.("A1",lesson.id,{percent,practice:practiceScore,trainer:trainerScore,assessment:assessmentScore,weakSpots:Object.fromEntries(weakTags),nextLessonId:lesson.nextLessonId});r.innerHTML=`<div class="a1-lesson">${stepper(stage)}<div class="a1-result"><div class="a1-score">${percent}%</div><h2>${esc(msg)}</h2><p>${esc(t.resultTitle)}: ${assessmentScore}/${total} · ${U().practice}: ${practiceScore}/6 · ${U().trainer}: ${trainerScore}/8</p><h3>${U().weak}</h3><div class="a1-weak-list">${weakTags.length?weakTags.map(([k,v])=>`<span>${esc(k)} · ${v}</span>`).join(""):esc(U().noWeak)}</div><div class="a1-result-actions">${weakTags.length?`<button class="grammar-primary" id="a1Review">${U().reviewErrors}</button>`:""}<button id="a1Repeat">${U().repeat}</button><button id="a1Route">${U().route}</button></div></div></div>`;document.getElementById("a1Review")?.addEventListener("click",renderReview);document.getElementById("a1Repeat").onclick=()=>{practiceScore=trainerScore=assessmentScore=0;weak={};renderExplanation()};document.getElementById("a1Route").onclick=()=>window.openA1Curriculum?.();}
function renderReview(){stage="review";const r=root(),t=lesson.i18n[lang()]||lesson.i18n.ru,items=Object.entries(weak).sort((a,b)=>b[1]-a[1]);r.innerHTML=`<div class="a1-lesson">${stepper(stage)}<div class="a1-kicker">A1 · ${esc(t.reviewTitle)}</div><h2>${esc(t.reviewTitle)}</h2>${items.map(([tag,count])=>{const rule=t.rules[tagRule[tag]]||[tag,""];return`<article class="a1-review-card"><h3>${esc(rule[0])} <small>× ${count}</small></h3><p>${esc(rule[1])}</p></article>`}).join("")}<p><strong>${esc(t.nextTitle)}</strong><br>${esc(U().planned)}</p><div class="a1-result-actions"><button class="grammar-primary" id="a1RetryAssessment">${U().repeatAssessment}</button><button id="a1Route">${U().route}</button></div></div>`;document.getElementById("a1RetryAssessment").onclick=()=>{assessmentScore=0;weak={};runStage("assessment",10)};document.getElementById("a1Route").onclick=()=>window.openA1Curriculum?.();}
async function openLesson(id){try{const res=await fetch(DATA_URL,{cache:"no-store"});if(!res.ok)throw new Error("A1 lessons load failed");const data=await res.json();if(!data[id])return;lesson={id,...data[id]};practiceScore=trainerScore=assessmentScore=0;weak={};renderExplanation();}catch(e){console.error(e);}}
document.addEventListener("esprofe:a1Topic",e=>openLesson(e.detail?.topicId));document.addEventListener("esprofe:languageChanged",()=>{if(!lesson||root()?.style.display!=="block")return;if(stage==="explanation")renderExplanation();else if(stage==="examples")renderExamples();else if(stage==="review")renderReview();});window.openA1Lesson=openLesson;
})();