"use strict";
(function(){
const L={
ru:{title:"Прилагательные",intro:"Согласование прилагательных с существительными по роду и числу.",rule1:"Прилагательное согласуется с существительным в роде и числе. Прилагательные на -o имеют четыре формы: alto, alta, altos, altas.",rule2:"Прилагательные на -e и многие прилагательные на согласную имеют одну форму для мужского и женского рода: interesante, difícil. Во множественном числе добавляем -s после гласной и -es после согласной: interesantes, difíciles.",rule3:"Обычно прилагательное ставится после существительного: una casa blanca, un libro interesante.",examples:"Примеры",practice:"▶ Тренироваться",back:"← Назад",check:"Проверить",prompt:"Введите правильную форму прилагательного",correct:"Правильно!",answer:"Правильный ответ: ",result:"Результат",repeat:"Новая тренировка",lesson:"Вернуться к уроку",excellent:"Отлично. Материал усвоен.",good:"Хорошо, но повторите ошибки.",again:"Повторите правило и тренировку."},
uk:{title:"Прикметники",intro:"Узгодження прикметників з іменниками за родом і числом.",rule1:"Прикметник узгоджується з іменником у роді та числі. Прикметники на -o мають чотири форми: alto, alta, altos, altas.",rule2:"Прикметники на -e та багато прикметників на приголосну мають одну форму для чоловічого й жіночого роду: interesante, difícil. У множині додаємо -s після голосної та -es після приголосної: interesantes, difíciles.",rule3:"Зазвичай прикметник ставиться після іменника: una casa blanca, un libro interesante.",examples:"Приклади",practice:"▶ Тренуватися",back:"← Назад",check:"Перевірити",prompt:"Введіть правильну форму прикметника",correct:"Правильно!",answer:"Правильна відповідь: ",result:"Результат",repeat:"Нове тренування",lesson:"Повернутися до уроку",excellent:"Чудово. Матеріал засвоєно.",good:"Добре, але повторіть помилки.",again:"Повторіть правило і тренування."},
en:{title:"Adjectives",intro:"Agreement of adjectives with nouns in gender and number.",rule1:"An adjective agrees with its noun in gender and number. Adjectives ending in -o have four forms: alto, alta, altos, altas.",rule2:"Adjectives ending in -e and many ending in a consonant use the same masculine and feminine form: interesante, difícil. In the plural add -s after a vowel and -es after a consonant: interesantes, difíciles.",rule3:"Adjectives normally follow the noun: una casa blanca, un libro interesante.",examples:"Examples",practice:"▶ Practise",back:"← Back",check:"Check",prompt:"Enter the correct adjective form",correct:"Correct!",answer:"Correct answer: ",result:"Result",repeat:"New practice",lesson:"Back to lesson",excellent:"Excellent. Material mastered.",good:"Good, but review your mistakes.",again:"Review the rule and practise again."},
es:{title:"Adjetivos",intro:"Concordancia de los adjetivos con los sustantivos en género y número.",rule1:"El adjetivo concuerda con el sustantivo en género y número. Los adjetivos terminados en -o tienen cuatro formas: alto, alta, altos, altas.",rule2:"Los adjetivos terminados en -e y muchos terminados en consonante tienen la misma forma masculina y femenina: interesante, difícil. En plural añadimos -s después de vocal y -es después de consonante: interesantes, difíciles.",rule3:"Normalmente el adjetivo va después del sustantivo: una casa blanca, un libro interesante.",examples:"Ejemplos",practice:"▶ Practicar",back:"← Volver",check:"Comprobar",prompt:"Escribe la forma correcta del adjetivo",correct:"¡Correcto!",answer:"Respuesta correcta: ",result:"Resultado",repeat:"Nueva práctica",lesson:"Volver a la lección",excellent:"Excelente. Material dominado.",good:"Bien, pero repasa los errores.",again:"Repasa la regla y practica de nuevo."}}
const nouns=[
["un chico","m","s"],["una chica","f","s"],["unos chicos","m","p"],["unas chicas","f","p"],["un coche","m","s"],["dos coches","m","p"],["una casa","f","s"],["dos casas","f","p"],["un libro","m","s"],["unos libros","m","p"],["una película","f","s"],["unas películas","f","p"],["un examen","m","s"],["dos exámenes","m","p"],["una mesa","f","s"],["unas mesas","f","p"],["un perro","m","s"],["dos perros","m","p"],["una puerta","f","s"],["unas puertas","f","p"]];
const adjectives=[
{base:"alto",mS:"alto",fS:"alta",mP:"altos",fP:"altas"},{base:"bajo",mS:"bajo",fS:"baja",mP:"bajos",fP:"bajas"},{base:"blanco",mS:"blanco",fS:"blanca",mP:"blancos",fP:"blancas"},{base:"negro",mS:"negro",fS:"negra",mP:"negros",fP:"negras"},{base:"rojo",mS:"rojo",fS:"roja",mP:"rojos",fP:"rojas"},{base:"bonito",mS:"bonito",fS:"bonita",mP:"bonitos",fP:"bonitas"},{base:"pequeño",mS:"pequeño",fS:"pequeña",mP:"pequeños",fP:"pequeñas"},{base:"nuevo",mS:"nuevo",fS:"nueva",mP:"nuevos",fP:"nuevas"},{base:"interesante",mS:"interesante",fS:"interesante",mP:"interesantes",fP:"interesantes"},{base:"grande",mS:"grande",fS:"grande",mP:"grandes",fP:"grandes"},{base:"difícil",mS:"difícil",fS:"difícil",mP:"difíciles",fP:"difíciles"},{base:"fácil",mS:"fácil",fS:"fácil",mP:"fáciles",fP:"fáciles"}];
function makeBank(){const bank=[];nouns.forEach(([noun,g,n])=>adjectives.forEach(adj=>{const key=(g==="m"?"m":"f")+(n==="s"?"S":"P");bank.push({q:`${noun} ___ (${adj.base})`,a:adj[key]});}));return bank}
function shuffled(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a}
function lang(){return document.getElementById("language")?.value||"ru"}function t(k){return(L[lang()]||L.ru)[k]}
function close(){const r=document.getElementById("grammarSection");r.style.display="none";const tr=document.querySelector(".trainer");if(tr)tr.style.display="flex"}
function render(){const r=document.getElementById("grammarSection");if(!r)return;r.style.display="block";r.innerHTML=`<div class="grammar-header"><div><div class="grammar-kicker">📖 A1</div><h2>${t("title")}</h2><p>${t("intro")}</p></div><button id="adjBack">${t("back")}</button></div><div class="grammar-card"><p>${t("rule1")}</p><table class="grammar-table"><thead><tr><th>masculino singular</th><th>femenino singular</th><th>masculino plural</th><th>femenino plural</th></tr></thead><tbody><tr><td>alto</td><td>alta</td><td>altos</td><td>altas</td></tr><tr><td>blanco</td><td>blanca</td><td>blancos</td><td>blancas</td></tr></tbody></table><p>${t("rule2")}</p><p>${t("rule3")}</p><h3>${t("examples")}</h3><table class="grammar-table"><tbody><tr><td>un coche rojo</td><td>una casa roja</td></tr><tr><td>los coches rojos</td><td>las casas rojas</td></tr><tr><td>un libro interesante</td><td>unas películas interesantes</td></tr><tr><td>un examen difícil</td><td>dos exámenes difíciles</td></tr></tbody></table></div><button class="grammar-primary" id="adjPractice">${t("practice")}</button>`;document.getElementById("adjBack").onclick=close;document.getElementById("adjPractice").onclick=practice}
function practice(){const r=document.getElementById("grammarSection"),Q=shuffled(makeBank()).slice(0,12);let p=0,s=0;r.innerHTML=`<div class="grammar-header"><div><div class="grammar-kicker">🏋️ A1 · ${t("title")}</div><p>${t("prompt")}</p></div></div><div class="grammar-practice-card"><p id="adjProgress"></p><h3 id="adjQuestion"></h3><input id="adjAnswer" type="text" autocomplete="off"><button id="adjCheck" class="grammar-primary">${t("check")}</button><p id="adjResult"></p></div>`;const next=()=>{if(p>=Q.length)return finish(s,Q.length);document.getElementById("adjProgress").textContent=`${p+1} / ${Q.length}`;document.getElementById("adjQuestion").textContent=Q[p].q;const i=document.getElementById("adjAnswer");i.value="";i.disabled=false;document.getElementById("adjResult").textContent="";i.focus()};const check=()=>{const i=document.getElementById("adjAnswer");if(i.disabled)return;const a=i.value.trim().toLowerCase();if(!a)return;i.disabled=true;const ok=a===Q[p].a;if(ok)s++;document.getElementById("adjResult").textContent=ok?`✅ ${t("correct")}`:`❌ ${t("answer")}${Q[p].a}`;p++;setTimeout(next,650)};document.getElementById("adjCheck").onclick=check;document.getElementById("adjAnswer").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();check()}});next()}
function finish(s,total){const r=document.getElementById("grammarSection"),p=Math.round(s/total*100),m=p>=90?t("excellent"):p>=70?t("good"):t("again");r.innerHTML=`<div class="grammar-result-card"><div class="grammar-kicker">🏆 ${t("result")}</div><h2>${p}%</h2><p>${m}</p><div class="grammar-result-bar"><span style="width:${p}%"></span></div><button class="grammar-primary" id="adjRepeat">${t("repeat")}</button><button id="adjLesson">${t("lesson")}</button></div>`;document.getElementById("adjRepeat").onclick=practice;document.getElementById("adjLesson").onclick=render;if(window.progressRecordGrammar)window.progressRecordGrammar("adjectives",p,[])}
document.addEventListener("esprofe:subtopic",e=>{if(e.detail?.topic==="grammar"&&e.detail.subtopic==="adjectives"){const tr=document.querySelector(".trainer");if(tr)tr.style.display="none";render()}});document.addEventListener("esprofe:languageChanged",()=>{if(document.getElementById("grammarSection")?.style.display==="block"&&document.querySelector('.subtopic-chip.active')?.dataset.subtopic==="adjectives")render()});
})();