"use strict";

const grammarLessons = {
  presente: {
    title:{ru:"Presente: глаголы на -AR",uk:"Presente: дієслова на -AR",en:"Presente: -AR verbs",es:"Presente: verbos en -AR"},
    intro:{ru:"Сначала изучите правило, затем потренируйтесь и только после этого пройдите контроль.",uk:"Спочатку вивчіть правило, потім потренуйтеся і лише після цього пройдіть контроль.",en:"First learn the rule, then practise, and only after that take the assessment.",es:"Primero estudia la regla, después practica y finalmente realiza la evaluación."},
    rule:{ru:"У правильных глаголов на -AR убираем окончание -ar и добавляем окончания настоящего времени.",uk:"У правильних дієслів на -AR забираємо закінчення -ar і додаємо закінчення теперішнього часу.",en:"For regular -AR verbs, remove -ar and add the present-tense endings.",es:"En los verbos regulares en -AR, quitamos -ar y añadimos las terminaciones del presente."},
    endings:["-o","-as","-a","-amos","-áis","-an"],
    persons:["yo","tú","él / ella","nosotros","vosotros","ellos / ellas"],
    example:["hablo","hablas","habla","hablamos","habláis","hablan"]
  }
};

let grammarState = "study";
function gLang(){ return (document.getElementById("language")?.value)||"ru"; }
function gt(obj){ return obj?.[gLang()] || obj?.ru || ""; }
function renderGrammar(id="presente"){
  const lesson=grammarLessons[id]; const root=document.getElementById("grammarSection"); if(!lesson||!root)return;
  root.innerHTML=`<div class="grammar-header"><div><div class="grammar-kicker">📖 ${gLang()==="es"?"Gramática":gLang()==="en"?"Grammar":gLang()==="uk"?"Граматика":"Грамматика"}</div><h2>${gt(lesson.title)}</h2><p>${gt(lesson.intro)}</p></div><button id="grammarClose" type="button">${gLang()==="es"?"← Volver":gLang()==="en"?"← Back":gLang()==="uk"?"← Назад":"← Назад"}</button></div><div class="grammar-steps"><span class="active">1 · ${gLang()==="es"?"Estudiar":gLang()==="en"?"Study":gLang()==="uk"?"Вивчення":"Изучение"}</span><span>2 · ${gLang()==="es"?"Practicar":gLang()==="en"?"Practise":gLang()==="uk"?"Тренування":"Тренировка"}</span><span>3 · ${gLang()==="es"?"Evaluación":gLang()==="en"?"Assessment":gLang()==="uk"?"Контроль":"Контроль"}</span><span>4 · ${gLang()==="es"?"Resultado":gLang()==="en"?"Result":gLang()==="uk"?"Результат":"Результат"}</span></div><div class="grammar-card"><h3>${gLang()==="es"?"Regla":gLang()==="en"?"Rule":gLang()==="uk"?"Правило":"Правило"}</h3><p>${gt(lesson.rule)}</p><table class="grammar-table"><thead><tr><th>${gLang()==="es"?"Persona":gLang()==="en"?"Person":gLang()==="uk"?"Особа":"Лицо"}</th><th>${gLang()==="es"?"Terminación":gLang()==="en"?"Ending":gLang()==="uk"?"Закінчення":"Окончание"}</th><th>${gLang()==="es"?"Ejemplo":gLang()==="en"?"Example":gLang()==="uk"?"Приклад":"Пример"}</th></tr></thead><tbody>${lesson.persons.map((p,i)=>`<tr><td>${p}</td><td><strong>${lesson.endings[i]}</strong></td><td>${lesson.example[i]}</td></tr>`).join("")}</tbody></table><div class="grammar-tip">💡 ${gLang()==="es"?"Consejo: presta atención a vosotros (-áis).":gLang()==="en"?"Tip: pay attention to vosotros (-áis).":gLang()==="uk"?"Порада: зверніть увагу на vosotros (-áis).":"Совет: обратите внимание на vosotros (-áis)."}</div></div><button class="grammar-primary" id="grammarPractice">${gLang()==="es"?"▶ Practicar":gLang()==="en"?"▶ Practise":gLang()==="uk"?"▶ Тренуватися":"▶ Тренироваться"}</button>`;
  root.style.display="block";
  document.getElementById("grammarClose").onclick=closeGrammar;
  document.getElementById("grammarPractice").onclick=()=>startGrammarPractice(id);
}
function startGrammarPractice(id){
  const lesson=grammarLessons[id], root=document.getElementById("grammarSection"); grammarState="practice";
  root.innerHTML=`<div class="grammar-header"><div><div class="grammar-kicker">🏋️ ${gLang()==="es"?"Práctica":gLang()==="en"?"Practice":gLang()==="uk"?"Тренування":"Тренировка"}</div><h2>${gt(lesson.title)}</h2></div></div><div class="grammar-practice-card"><p id="gpProgress">1 / 6</p><h3 id="gpPrompt">${lesson.example[0]}</h3><p id="gpPerson">${lesson.persons[0]}</p><input id="gpAnswer" type="text" autocomplete="off"><button id="gpCheck" class="grammar-primary">${gLang()==="es"?"Comprobar":gLang()==="en"?"Check":gLang()==="uk"?"Перевірити":"Проверить"}</button><p id="gpResult"></p></div>`;
  let i=0,score=0;
  const next=()=>{if(i>=6){renderGrammarResult(id,score);return;} document.getElementById("gpProgress").textContent=`${i+1} / 6`;document.getElementById("gpPrompt").textContent="hablar";document.getElementById("gpPerson").textContent=lesson.persons[i];document.getElementById("gpAnswer").value="";document.getElementById("gpResult").textContent="";document.getElementById("gpAnswer").focus();};
  document.getElementById("gpCheck").onclick=()=>{const a=document.getElementById("gpAnswer").value.trim().toLowerCase();const r=document.getElementById("gpResult");if(!a)return;r.textContent=a===lesson.example[i]?"✅ "+(gLang()==="en"?"Correct!":gLang()==="uk"?"Правильно!":gLang()==="es"?"¡Correcto!":"Правильно!"):"❌ "+(gLang()==="en"?"Correct answer: ":gLang()==="uk"?"Правильна відповідь: ":gLang()==="es"?"Respuesta correcta: ":"Правильный ответ: ")+lesson.example[i];if(a===lesson.example[i])score++;i++;setTimeout(next,650);}; next();
}
function renderGrammarResult(id,score){const root=document.getElementById("grammarSection"),p=Math.round(score/6*100),l=grammarLessons[id];let msg=p>=90?(gLang()==="en"?"Excellent. You can continue.":gLang()==="uk"?"Чудово. Можна переходити далі.":gLang()==="es"?"Excelente. Puedes continuar.":"Отлично. Можно переходить дальше."):p>=70?(gLang()==="en"?"Good, but review the mistakes.":gLang()==="uk"?"Добре, але повторіть помилки.":gLang()==="es"?"Bien, pero repasa los errores.":"Хорошо, но повторите ошибки."):(gLang()==="en"?"Repeat the rule and practise again.":gLang()==="uk"?"Повторіть правило і потренуйтеся ще раз.":gLang()==="es"?"Repite la regla y practica de nuevo.":"Повторите правило и потренируйтесь ещё раз.");root.innerHTML=`<div class="grammar-result-card"><div class="grammar-kicker">🏆 ${gLang()==="en"?"Result":gLang()==="uk"?"Результат":"Результат"}</div><h2>${p}%</h2><p>${msg}</p><div class="grammar-result-bar"><span style="width:${p}%"></span></div><button class="grammar-primary" id="grammarRetry">${gLang()==="en"?"Repeat":gLang()==="uk"?"Повторити":gLang()==="es"?"Repetir":"Повторить"}</button><button id="grammarBack">${gLang()==="en"?"Back to lesson":gLang()==="uk"?"До уроку":gLang()==="es"?"Volver a la lección":"Вернуться к уроку"}</button></div>`;document.getElementById("grammarRetry").onclick=()=>startGrammarPractice(id);document.getElementById("grammarBack").onclick=()=>renderGrammar(id);if(window.progressRecordGrammar)window.progressRecordGrammar(id,p);}
function closeGrammar(){document.getElementById("grammarSection").style.display="none";document.querySelector(".trainer")?.scrollIntoView({behavior:"smooth",block:"start"});}
function openGrammar(id="presente"){document.querySelector(".trainer").style.display="none";renderGrammar(id);document.getElementById("grammarSection")?.scrollIntoView({behavior:"smooth",block:"start"});}
document.addEventListener("esprofe:subtopic",e=>{if(e.detail?.topic==="grammar")openGrammar(e.detail.subtopic||"presente");});
document.addEventListener("esprofe:languageChanged",()=>{if(document.getElementById("grammarSection")?.style.display==="block")renderGrammar("presente");});
