"use strict";
(function(){
const T={
ru:{title:"Притяжательные прилагательные",intro:"Учимся использовать mi, tu, su, nuestro/a, vuestro/a и их формы множественного числа.",rule1:"Притяжательное слово ставится перед существительным: mi casa, tus libros, nuestra profesora.",rule2:"mi, tu, su меняются только по числу: mi/mis, tu/tus, su/sus. Формы nuestro/a/os/as и vuestro/a/os/as согласуются с существительным по роду и числу.",rule3:"su/sus может означать его, её, Ваш, их. Значение определяется контекстом.",practice:"▶ Тренироваться",back:"← Назад",check:"Проверить",prompt:"Введите подходящую притяжательную форму",correct:"Правильно!",answer:"Правильный ответ: ",result:"Результат",repeat:"Новая тренировка",lesson:"Вернуться к уроку",excellent:"Отлично. Материал усвоен.",good:"Хорошо, но повторите ошибки.",again:"Повторите правило и тренировку."},
uk:{title:"Присвійні прикметники",intro:"Вчимося використовувати mi, tu, su, nuestro/a, vuestro/a та їхні форми множини.",rule1:"Присвійне слово ставиться перед іменником: mi casa, tus libros, nuestra profesora.",rule2:"mi, tu, su змінюються лише за числом: mi/mis, tu/tus, su/sus. Форми nuestro/a/os/as і vuestro/a/os/as узгоджуються з іменником у роді та числі.",rule3:"su/sus може означати його, її, Ваш, їхній. Значення визначається контекстом.",practice:"▶ Тренуватися",back:"← Назад",check:"Перевірити",prompt:"Введіть відповідну присвійну форму",correct:"Правильно!",answer:"Правильна відповідь: ",result:"Результат",repeat:"Нове тренування",lesson:"Повернутися до уроку",excellent:"Чудово. Матеріал засвоєно.",good:"Добре, але повторіть помилки.",again:"Повторіть правило і тренування."},
en:{title:"Possessive adjectives",intro:"Learn to use mi, tu, su, nuestro/a, vuestro/a and their plural forms.",rule1:"The possessive goes before the noun: mi casa, tus libros, nuestra profesora.",rule2:"mi, tu and su change only for number: mi/mis, tu/tus, su/sus. nuestro/a/os/as and vuestro/a/os/as agree with the noun in gender and number.",rule3:"su/sus can mean his, her, your formal or their. Context determines the meaning.",practice:"▶ Practise",back:"← Back",check:"Check",prompt:"Enter the correct possessive form",correct:"Correct!",answer:"Correct answer: ",result:"Result",repeat:"New practice",lesson:"Back to lesson",excellent:"Excellent. Material mastered.",good:"Good, but review your mistakes.",again:"Review the rule and practise again."},
es:{title:"Adjetivos posesivos",intro:"Aprende a usar mi, tu, su, nuestro/a, vuestro/a y sus formas plurales.",rule1:"El posesivo va delante del sustantivo: mi casa, tus libros, nuestra profesora.",rule2:"mi, tu y su cambian solo en número: mi/mis, tu/tus, su/sus. nuestro/a/os/as y vuestro/a/os/as concuerdan con el sustantivo en género y número.",rule3:"su/sus puede significar de él, de ella, de usted o de ellos/ellas. El contexto aclara el significado.",practice:"▶ Practicar",back:"← Volver",check:"Comprobar",prompt:"Escribe la forma posesiva correcta",correct:"¡Correcto!",answer:"Respuesta correcta: ",result:"Resultado",repeat:"Nueva práctica",lesson:"Volver a la lección",excellent:"Excelente. Material dominado.",good:"Bien, pero repasa los errores.",again:"Repasa la regla y practica de nuevo."}}
const bank=[
{q:"Yo tengo una casa. ___ casa es pequeña.",a:"mi"},{q:"Yo tengo dos hermanos. ___ hermanos viven en Madrid.",a:"mis"},{q:"Tú tienes un coche. ___ coche es nuevo.",a:"tu"},{q:"Tú tienes dos libros. ___ libros están aquí.",a:"tus"},{q:"Ana tiene una hermana. ___ hermana estudia medicina.",a:"su"},{q:"Carlos tiene dos hijos. ___ hijos van al colegio.",a:"sus"},{q:"Nosotros tenemos una profesora. ___ profesora se llama Marta.",a:"nuestra"},{q:"Nosotros tenemos un profesor. ___ profesor es de Sevilla.",a:"nuestro"},{q:"Nosotros tenemos dos clases. ___ clases empiezan a las nueve.",a:"nuestras"},{q:"Nosotros tenemos dos amigos. ___ amigos viven cerca.",a:"nuestros"},{q:"Vosotros tenéis una casa. ___ casa está en Valencia.",a:"vuestra"},{q:"Vosotros tenéis un perro. ___ perro es muy tranquilo.",a:"vuestro"},{q:"Vosotros tenéis dos hijas. ___ hijas estudian español.",a:"vuestras"},{q:"Vosotros tenéis dos hijos. ___ hijos juegan al fútbol.",a:"vuestros"},{q:"Ellos tienen una empresa. ___ empresa está en Barcelona.",a:"su"},{q:"Ellas tienen dos coches. ___ coches son pequeños.",a:"sus"},{q:"Usted tiene una cita. ___ cita es a las diez.",a:"su"},{q:"Ustedes tienen dos reservas. ___ reservas están confirmadas.",a:"sus"},{q:"Yo busco las llaves. ¿Dónde están ___ llaves?",a:"mis"},{q:"Tú llamas a tu madre. ¿Cuál es ___ número?",a:"su"}];
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function lang(){return document.getElementById("language")?.value||"ru"}function t(k){return(T[lang()]||T.ru)[k]}
function close(){const r=document.getElementById("grammarSection");r.style.display="none";const tr=document.querySelector(".trainer");if(tr)tr.style.display="flex"}
function render(){const r=document.getElementById("grammarSection");if(!r)return;r.style.display="block";r.innerHTML=`<div class="grammar-header"><div><div class="grammar-kicker">📖 A1</div><h2>${t("title")}</h2><p>${t("intro")}</p></div><button id="posBack">${t("back")}</button></div><div class="grammar-card"><p>${t("rule1")}</p><p>${t("rule2")}</p><p>${t("rule3")}</p><table class="grammar-table"><thead><tr><th>persona</th><th>singular</th><th>plural</th></tr></thead><tbody><tr><td>yo</td><td>mi</td><td>mis</td></tr><tr><td>tú</td><td>tu</td><td>tus</td></tr><tr><td>él / ella / usted</td><td>su</td><td>sus</td></tr><tr><td>nosotros/as</td><td>nuestro / nuestra</td><td>nuestros / nuestras</td></tr><tr><td>vosotros/as</td><td>vuestro / vuestra</td><td>vuestros / vuestras</td></tr><tr><td>ellos / ellas / ustedes</td><td>su</td><td>sus</td></tr></tbody></table></div><button class="grammar-primary" id="posPractice">${t("practice")}</button>`;document.getElementById("posBack").onclick=close;document.getElementById("posPractice").onclick=practice}
function practice(){const r=document.getElementById("grammarSection"),Q=shuffle(bank).slice(0,12);let p=0,s=0;r.innerHTML=`<div class="grammar-header"><div><div class="grammar-kicker">🏋️ A1 · ${t("title")}</div><p>${t("prompt")}</p></div></div><div class="grammar-practice-card"><p id="posProgress"></p><h3 id="posQuestion"></h3><input id="posAnswer" type="text" autocomplete="off"><button id="posCheck" class="grammar-primary">${t("check")}</button><p id="posResult"></p></div>`;const next=()=>{if(p>=Q.length)return finish(s,Q.length);document.getElementById("posProgress").textContent=`${p+1} / ${Q.length}`;document.getElementById("posQuestion").textContent=Q[p].q;const i=document.getElementById("posAnswer");i.value="";i.disabled=false;document.getElementById("posResult").textContent="";i.focus()};const check=()=>{const i=document.getElementById("posAnswer");if(i.disabled)return;const a=i.value.trim().toLowerCase();if(!a)return;i.disabled=true;const ok=a===Q[p].a;if(ok)s++;document.getElementById("posResult").textContent=ok?`✅ ${t("correct")}`:`❌ ${t("answer")}${Q[p].a}`;p++;setTimeout(next,650)};document.getElementById("posCheck").onclick=check;document.getElementById("posAnswer").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();check()}});next()}
function finish(s,total){const r=document.getElementById("grammarSection"),p=Math.round(s/total*100),m=p>=90?t("excellent"):p>=70?t("good"):t("again");r.innerHTML=`<div class="grammar-result-card"><div class="grammar-kicker">🏆 ${t("result")}</div><h2>${p}%</h2><p>${m}</p><div class="grammar-result-bar"><span style="width:${p}%"></span></div><button class="grammar-primary" id="posRepeat">${t("repeat")}</button><button id="posLesson">${t("lesson")}</button></div>`;document.getElementById("posRepeat").onclick=practice;document.getElementById("posLesson").onclick=render;if(window.progressRecordGrammar)window.progressRecordGrammar("possessives",p,[])}
document.addEventListener("esprofe:subtopic",e=>{if(e.detail?.topic==="grammar"&&e.detail.subtopic==="possessives"){const tr=document.querySelector(".trainer");if(tr)tr.style.display="none";render()}});document.addEventListener("esprofe:languageChanged",()=>{if(document.getElementById("grammarSection")?.style.display==="block"&&document.querySelector('.subtopic-chip.active')?.dataset.subtopic==="possessives")render()});
})();