"use strict";

const ESPROFE_PROGRESS_KEY = "esprofe_progress_v1";
const progressLabels = {
  ru: { title:"Мой прогресс", mastered:"Освоено", review:"Повторить", weak:"Слабые места", recommendation:"Рекомендация", next:"Продолжить обучение", good:"Материал усвоен", repeat:"Рекомендуется повторение", learnAgain:"Нужно повторить обучение", correct:"Правильных", mistakes:"Ошибок", details:"Подробнее", noWeak:"Пока нет слабых мест", grammar:"Грамматика", topics:"Темы", recent:"Последний результат" },
  uk: { title:"Мій прогрес", mastered:"Освоєно", review:"Повторити", weak:"Слабкі місця", recommendation:"Рекомендація", next:"Продовжити навчання", good:"Матеріал засвоєно", repeat:"Рекомендується повторення", learnAgain:"Потрібно повторити навчання", correct:"Правильних", mistakes:"Помилок", details:"Детальніше", noWeak:"Поки немає слабких місць", grammar:"Граматика", topics:"Теми", recent:"Останній результат" },
  en: { title:"My progress", mastered:"Mastered", review:"Review", weak:"Weak spots", recommendation:"Recommendation", next:"Continue learning", good:"Material mastered", repeat:"Review recommended", learnAgain:"Repeat the lesson", correct:"Correct", mistakes:"Mistakes", details:"Details", noWeak:"No weak spots yet", grammar:"Grammar", topics:"Topics", recent:"Latest result" },
  es: { title:"Mi progreso", mastered:"Dominado", review:"Revisar", weak:"Puntos débiles", recommendation:"Recomendación", next:"Continuar aprendiendo", good:"Material dominado", repeat:"Se recomienda repasar", learnAgain:"Hay que repetir la lección", correct:"Correctas", mistakes:"Errores", details:"Detalles", noWeak:"Todavía no hay puntos débiles", grammar:"Gramática", topics:"Temas", recent:"Último resultado" }
};
function getProgressData(){try{return JSON.parse(localStorage.getItem(ESPROFE_PROGRESS_KEY))||{correct:0,mistakes:0,weak:{},tests:[],grammar:{}};}catch(_){return{correct:0,mistakes:0,weak:{},tests:[],grammar:{}};}}
function saveProgressData(data){localStorage.setItem(ESPROFE_PROGRESS_KEY,JSON.stringify(data));}
function progressRecordAnswer(verb,person,isCorrect){const data=getProgressData();const key=`${verb.id??verb.infinitive}:${person}`;if(isCorrect){data.correct++;if(data.weak[key]){data.weak[key].mistakes=Math.max(0,(data.weak[key].mistakes||1)-1);if(data.weak[key].mistakes===0)delete data.weak[key];}}else{data.mistakes++;if(!data.weak[key])data.weak[key]={verb:verb.infinitive,person,mistakes:0};data.weak[key].mistakes++;}saveProgressData(data);renderProgress();}
function progressRecordTest(percent){const data=getProgressData();data.tests.push({percent,date:new Date().toISOString()});if(data.tests.length>20)data.tests.shift();saveProgressData(data);renderProgress();}
function progressRecordGrammar(id,percent,personResults){const data=getProgressData();data.grammar=data.grammar||{};data.grammar[id]={percent,date:new Date().toISOString(),persons:(personResults||[]).map(r=>({correct:r.correct||0,total:r.total||0}))};saveProgressData(data);renderProgress();}
function getProgressSummary(){const data=getProgressData();const total=data.correct+data.mistakes;const mastery=total?Math.round(data.correct/total*100):0;const weakEntries=Object.values(data.weak).sort((a,b)=>b.mistakes-a.mistakes);let recommendation="start";if(mastery>=90)recommendation="good";else if(mastery>=70)recommendation="repeat";else if(total>0)recommendation="learnAgain";return{data,mastery,weakEntries,recommendation};}
function renderProgress(){const panel=document.getElementById("progressPanel");if(!panel)return;const lang=document.getElementById("language")?.value||"ru";const t=progressLabels[lang]||progressLabels.ru;const{data,mastery,weakEntries,recommendation}=getProgressSummary();const recommendationText=recommendation==="good"?t.good:recommendation==="repeat"?t.repeat:recommendation==="learnAgain"?t.learnAgain:t.next;const grammarEntries=Object.entries(data.grammar||{});const latestTest=data.tests?.length?data.tests[data.tests.length-1]:null;const weakHtml=weakEntries.length?weakEntries.slice(0,3).map(w=>`<span class="progress-weak-chip">⚠ ${w.verb} · ${w.person} <strong>${w.mistakes}</strong></span>`).join(""):`<span class="progress-empty">${t.noWeak}</span>`;const grammarHtml=grammarEntries.length?grammarEntries.map(([id,g])=>`<span class="progress-topic-chip"><strong>${id}</strong> ${g.percent}%</span>`).join(""):"";panel.innerHTML=`<div class="progress-top"><div class="progress-title">📊 ${t.title}</div><strong>${mastery}%</strong></div><div class="progress-bar"><span style="width:${mastery}%"></span></div><div class="progress-stats"><span>🟢 ${t.mastered}: ${mastery}%</span><span>🟡 ${t.review}: ${data.mistakes}</span><span>🔴 ${t.weak}: ${weakEntries.length}</span></div><div class="progress-bottom"><span>${t.recommendation}: <strong>${recommendationText}</strong></span><span>${t.correct}: ${data.correct} · ${t.mistakes}: ${data.mistakes}${latestTest?` · ${t.recent}: ${latestTest.percent}%`:""}</span></div><details class="progress-details"><summary>${t.details}</summary><div class="progress-detail-section"><strong>${t.weak}</strong><div class="progress-chip-list">${weakHtml}</div></div>${grammarEntries.length?`<div class="progress-detail-section"><strong>${t.grammar} · ${t.topics}</strong><div class="progress-chip-list">${grammarHtml}</div></div>`:""}</details>`;}
document.addEventListener("esprofe:languageChanged",renderProgress);document.addEventListener("DOMContentLoaded",renderProgress);window.renderProgress=renderProgress;window.progressRecordAnswer=progressRecordAnswer;window.progressRecordTest=progressRecordTest;window.progressRecordGrammar=progressRecordGrammar;
