"use strict";
const ESPROFE_STUDENT_KEY="esprofe_student_v1";
const studentLabels={
ru:{profile:"Личный кабинет",name:"Ученик",level:"Уровень",current:"Сейчас",continue:"Продолжить обучение",edit:"Изменить имя",save:"Сохранить",placeholder:"Введите имя",localNote:"Прогресс пока хранится на этом устройстве.",alphabet:"A1 · Алфавит и произношение",greetings:"A1 · Приветствия и прощания",route:"Маршрут курса A1"},
uk:{profile:"Особистий кабінет",name:"Учень",level:"Рівень",current:"Зараз",continue:"Продовжити навчання",edit:"Змінити ім’я",save:"Зберегти",placeholder:"Введіть ім’я",localNote:"Прогрес поки зберігається на цьому пристрої.",alphabet:"A1 · Алфавіт і вимова",greetings:"A1 · Привітання і прощання",route:"Маршрут курсу A1"},
en:{profile:"Student profile",name:"Student",level:"Level",current:"Now",continue:"Continue learning",edit:"Edit name",save:"Save",placeholder:"Enter name",localNote:"Progress is currently stored on this device.",alphabet:"A1 · Alphabet and pronunciation",greetings:"A1 · Greetings and farewells",route:"A1 course route"},
es:{profile:"Área personal",name:"Estudiante",level:"Nivel",current:"Ahora",continue:"Continuar aprendiendo",edit:"Cambiar nombre",save:"Guardar",placeholder:"Escribe tu nombre",localNote:"Por ahora, el progreso se guarda en este dispositivo.",alphabet:"A1 · Alfabeto y pronunciación",greetings:"A1 · Saludos y despedidas",route:"Ruta del curso A1"}
};
function normalizeStudent(p){p=p||{};return{name:p.name||"",level:p.level||"A1",studentId:p.studentId||null,currentLesson:p.currentLesson||"alphabet-pronunciation",completedLessons:Array.isArray(p.completedLessons)?p.completedLessons:[]};}
function getStudentProfile(){try{return normalizeStudent(JSON.parse(localStorage.getItem(ESPROFE_STUDENT_KEY)));}catch(_){return normalizeStudent({});}}
function saveStudentProfile(profile){localStorage.setItem(ESPROFE_STUDENT_KEY,JSON.stringify(normalizeStudent(profile)));document.dispatchEvent(new CustomEvent("esprofe:studentChanged",{detail:profile}));}
function setStudentCurrentLesson(lessonId){const p=getStudentProfile();p.currentLesson=lessonId;saveStudentProfile(p);}
function markStudentLessonComplete(lessonId,nextLessonId){const p=getStudentProfile();p.completedLessons=Array.from(new Set([...(p.completedLessons||[]),lessonId]));if(nextLessonId)p.currentLesson=nextLessonId;saveStudentProfile(p);}
function resolveCurrentLesson(){const step=window.getNextLearningStep?.();if(step?.subtopic&&step.subtopic!=="route")return step.subtopic;return getStudentProfile().currentLesson||"alphabet-pronunciation";}
function currentLabel(id,t){if(id==="alphabet-pronunciation")return t.alphabet;if(id==="greetings-farewells")return t.greetings;return t.route;}
function renderStudentProfile(){const panel=document.getElementById("studentProfile");if(!panel)return;const code=document.getElementById("language")?.value||"ru",t=studentLabels[code]||studentLabels.ru,p=getStudentProfile(),display=p.name||t.name,currentId=resolveCurrentLesson(),label=currentLabel(currentId,t);panel.innerHTML=`<div class="student-profile-head"><div><span class="student-profile-kicker">👤 ${t.profile}</span><strong>${display}</strong></div><span class="student-level">${t.level} ${p.level}</span></div><div class="student-profile-body"><div><small>${t.current}</small><strong>${label}</strong></div><button type="button" id="studentContinueBtn">${t.continue} →</button></div><details class="student-profile-settings"><summary>${t.edit}</summary><div class="student-name-form"><input id="studentNameInput" type="text" maxlength="40" placeholder="${t.placeholder}" value="${p.name||""}"><button type="button" id="studentNameSave">${t.save}</button></div><p>${t.localNote}</p></details>`;document.getElementById("studentContinueBtn")?.addEventListener("click",()=>document.dispatchEvent(new CustomEvent("esprofe:progressAction",{detail:{topic:"a1",subtopic:currentId}})));document.getElementById("studentNameSave")?.addEventListener("click",()=>{const n=getStudentProfile();n.name=(document.getElementById("studentNameInput")?.value||"").trim();saveStudentProfile(n);renderStudentProfile();});}
document.addEventListener("DOMContentLoaded",renderStudentProfile);document.addEventListener("esprofe:languageChanged",renderStudentProfile);document.addEventListener("esprofe:studentChanged",renderStudentProfile);document.addEventListener("esprofe:progressChanged",renderStudentProfile);document.getElementById("language")?.addEventListener("change",()=>setTimeout(renderStudentProfile,0));window.getStudentProfile=getStudentProfile;window.saveStudentProfile=saveStudentProfile;window.setStudentCurrentLesson=setStudentCurrentLesson;window.markStudentLessonComplete=markStudentLessonComplete;window.renderStudentProfile=renderStudentProfile;